name: deploy
on:
  push:
    branches:
      - main


permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    # env:
    #   IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/mlops

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - run: echo "IMAGE_NAME=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          context: ./tp1
          file: ./tp1/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      # - name: deploy
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.VM_HOST }}
      #     username: ${{ secrets.VM_USER }}
      #     key: ${{ secrets.VM_SSH_KEY }}
      #     script: |
      #       docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      #       docker pull ghcr.io/${{ github.repository }}:latest
      #       docker stop mlops-app || true
      #       docker rm mlops-app || true
      #       docker run -d --name mlops-app -p 80:80 ghcr.io/${{ github.repository }}:latest
